<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="macros">
<!-- ############################################ 
       Macro - servo
     ############################################ -->

  <xacro:property name="servowidth"      value="0.04" />
  <xacro:property name="servolen"        value="0.04" />
  <xacro:property name="servothick"      value="0.02" />
  <xacro:property name="servo_velocity"  value="${60/180*pi/0.16}" />
  <xacro:property name="servo_effort"    value="1000.0" />  

  <xacro:macro name="servo" params="suffix">
    <link name="servo_${suffix}_link">
    <visual>
      <geometry>
        <box size="${servolen} ${servowidth} ${servothick}"/>
      </geometry>
      <origin rpy="0 0 0" xyz="0 0 0.0"/>   
      <material name="black"/>
    </visual>
    <collision>
      <geometry>
        <box size="${servolen} ${servowidth} ${servothick}"/>
      </geometry>
      <origin rpy="0 0 0" xyz="0 0 0.0"/>   
    </collision>
    </link>
  </xacro:macro>

  <!-- ############################################ 
       Parameters - for leg
       ############################################ -->
  <xacro:property name="pi"               value="3.14159265359" />
  <xacro:property name="hip_length"       value="0.045" />
  <xacro:property name="hip_radius"       value="0.0127" />
  <xacro:property name="hip_mass"         value="0.03" />  
  <xacro:property name="thigh_length"     value="0.15" />
  <xacro:property name="thigh_width"      value="0.035" />
  <xacro:property name="thigh_thickness"  value="0.006" />
  <xacro:property name="thigh_mass"       value="0.03" />
  <xacro:property name="x_offset_hip_to_thigh" value="0.023" />
  <xacro:property name="servo_velocity"  value="${60/180*pi/0.16}" />
  <xacro:property name="servo_effort"    value="1000.0" />
  <xacro:property name="gap_hip_to_thigh" value="0.015" />
  <xacro:property name="min_angle_thigh_joint" value="-0.5" />
  <xacro:property name="max_angle_thigh_joint" value="${pi/2}" />  
  <xacro:property name="leg_length"       value="0.14" />
  <xacro:property name="leg_radius"       value="0.0127" />
  <xacro:property name="leg_mass"         value="0.03" />
  <xacro:property name="x_offset_thigh_to_leg" value="0.023" />
  <xacro:property name="gap_thigh_to_leg" value="0.015" />
  <xacro:property name="min_angle_leg_joint" value="-${pi/2}" />
  <xacro:property name="max_angle_leg_joint" value="${pi/2}" />    
  <!-- ############################################ 
       Macro - leg
       ############################################ -->
  
  <xacro:macro name="leg" params="prefix">  
    <link name="${prefix}_hip_link">
      <visual>
        <geometry>
          <cylinder length="${hip_length}" radius="${hip_radius}"/>
        </geometry>
        <origin rpy="0 0 0" xyz="0 0 0.0"/>   
        <material name="blue"/>
      </visual>
      <collision>
        <geometry>
          <cylinder length="${hip_length}" radius="${hip_radius}"/>
        </geometry>
        <origin rpy="0 0 0" xyz="0 0 0.0"/>   
      </collision>
      <inertial>
        <mass value="${hip_mass}"/>
        <inertia ixx="0.4" ixy="0.0" ixz="0.0" iyy="0.4" iyz="0.0" izz="0.2"/>
      </inertial>
    </link>
  
    <link name="${prefix}_thigh_link">
      <visual>
        <geometry>
          <box size="${thigh_length} ${thigh_width} ${thigh_thickness}"/>
        </geometry>
        <material name="white"/>
        <origin rpy="0 0 0" xyz="${thigh_length/2-x_offset_hip_to_thigh} 0 -${gap_hip_to_thigh}"/>   
      </visual>
      <collision>
        <geometry>
          <box size="${thigh_length} ${thigh_width} ${thigh_thickness}"/>
        </geometry>
        <material name="white"/>
        <origin rpy="0 0 0" xyz="${thigh_length/2-x_offset_hip_to_thigh} 0 -${gap_hip_to_thigh}"/>   
      </collision>
      <inertial>
        <mass value="${thigh_mass}"/>
        <inertia ixx="0.4" ixy="0.0" ixz="0.0" iyy="0.4" iyz="0.0" izz="0.2"/>
      </inertial>
    </link>
    <joint name="${prefix}_hip_to_thigh" type="revolute">
      <parent link="${prefix}_hip_link"/>
      <child link="${prefix}_thigh_link"/>
      <origin xyz="0 0 -${hip_length/2+thigh_thickness/2}"/>
      <axis xyz="0 1 0"/>
      <limit effort="${servo_effort}" lower="${min_angle_thigh_joint}" upper="${max_angle_thigh_joint}" velocity="${servo_velocity}"/>    
    </joint>
      <link name="${prefix}_leg_link">
      <visual>
        <geometry>
          <cylinder length="${leg_length}" radius="${leg_radius}"/>
        </geometry>
        <material name="white"/>
        <origin rpy="0 0 0" xyz="0 0 -${leg_length/2}"/>   
      </visual>
      <collision>
        <geometry>
          <cylinder length="${leg_length}" radius="${leg_radius}"/>
        </geometry>
        <origin rpy="0 0 0" xyz="0 0 -${leg_length/2}"/>   
      </collision>    
      <inertial>
        <mass value="${leg_mass}"/>
        <inertia ixx="0.4" ixy="0.0" ixz="0.0" iyy="0.4" iyz="0.0" izz="0.2"/>
      </inertial>    
    </link>
  
    <joint name="${prefix}_thigh_to_leg" type="revolute">
      <parent link="${prefix}_thigh_link"/>
      <child link="${prefix}_leg_link"/>
      <origin xyz="${thigh_length-x_offset_hip_to_thigh-x_offset_thigh_to_leg} 0 -${gap_hip_to_thigh+thigh_thickness+gap_thigh_to_leg}"/>
      <axis xyz="0 1 0"/>
      <limit effort="${servo_effort}" lower="${min_angle_leg_joint}" upper="${max_angle_leg_joint}" velocity="${servo_velocity}"/>
    </joint>
  </xacro:macro>

  <!-- ############################################ 
       Macro - left leg
       ############################################ -->
  <xacro:macro name="left_leg" params="prefix">    
    <xacro:servo suffix="${prefix}"></xacro:servo>
    <xacro:leg prefix="${prefix}"></xacro:leg>
    <joint name="${prefix}_hip_joint" type="fixed">
      <parent link="servo_${prefix}_link"/>
      <child link="${prefix}_hip_link"/>
      <origin xyz="0 0 0"/>
    </joint>
  </xacro:macro>
</robot>
