<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="quadruped">
  <!-- ############################################ 
       include other xacro files
       ############################################ -->
  <xacro:include filename="$(cwd)/urdf/colors.xacro" />
  <xacro:include filename="$(cwd)/urdf/macros.xacro" />
  
  <!-- ############################################ 
       Parameters
       ############################################ -->
  
  <xacro:property name="bodywidth"       value="0.20" />
  <xacro:property name="bodylen"         value="0.31" />
  <xacro:property name="bodythick"       value="0.006" />
  <xacro:property name="legbaseoffset"   value="0.053" />
  <xacro:property name="body_mass"       value="2" />  
  <!-- ############################################ 
       Base
       ############################################ -->

  <link name="base_link">
    <visual>
      <geometry>
        <box size="${bodylen} ${bodywidth} ${bodythick}"/>
      </geometry>
      <origin rpy="0 0 0" xyz="0 0 0.0"/>   
      <material name="white"/>
    </visual>
    <collision>
      <geometry>
        <box size="${bodylen} ${bodywidth} ${bodythick}"/>
      </geometry>
      <origin rpy="0 0 0" xyz="0 0 0.0"/>   
    </collision>
      <inertial>
        <mass value="${body_mass}"/>
        <inertia ixx="0.4" ixy="0.0" ixz="0.0" iyy="0.4" iyz="0.0" izz="0.2"/>
      </inertial>
  </link>

  
  <!-- ############################################ 
       leg - front left
       ############################################ -->  

  <xacro:leg prefix="front_left"></xacro:leg>
  <joint name="base_front_left_joint" type="revolute">
    <parent link="base_link"/>
    <child link="front_left_hip_link"/>
    <origin xyz="${bodylen/2-servolen/2} ${bodywidth/2-servowidth/2} -${legbaseoffset}"/>
    <axis xyz="1 0 0" />
    <limit effort="${servo_effort}" lower="-0.785" upper="0.785" velocity="${servo_velocity}"/>
  </joint>

  <!-- ############################################ 
       leg - front right
       ############################################ -->  

  <xacro:leg prefix="front_right"></xacro:leg>

  <joint name="base_front_right_joint" type="revolute">
    <parent link="base_link"/>
    <child link="front_right_hip_link"/>
    <origin xyz="${bodylen/2-servolen/2} -${bodywidth/2-servowidth/2} -${legbaseoffset}"/>
    <axis xyz="-1 0 0" />
    <limit effort="${servo_effort}" lower="-0.785" upper="0.785" velocity="${servo_velocity}"/>
  </joint>

  <!-- ############################################ 
       leg - rear left
       ############################################ -->  

  <xacro:leg prefix="rear_left"></xacro:leg>

  <joint name="base_rear_left_joint" type="revolute">
    <parent link="base_link"/>
    <child link="rear_left_hip_link"/>
    <origin xyz="-${bodylen/2-servolen/2} ${bodywidth/2-servowidth/2} -${legbaseoffset}"/>
    <axis xyz="1 0 0" />
    <limit effort="${servo_effort}" lower="-0.785" upper="0.785" velocity="${servo_velocity}"/>
  </joint>

  <!-- ############################################ 
       leg - rear right
       ############################################ -->  

  <xacro:leg prefix="rear_right"></xacro:leg>

  <joint name="base_rear_right_joint" type="revolute">
    <parent link="base_link"/>
    <child link="rear_right_hip_link"/>
    <origin xyz="-${bodylen/2-servolen/2} -${bodywidth/2-servowidth/2} -${legbaseoffset}"/>
    <axis xyz="-1 0 0" />
    <limit effort="${servo_effort}" lower="-0.785" upper="0.785" velocity="${servo_velocity}"/>
  </joint>  
</robot> 
